### ISSUE TITLE
add my name to LICENSE or else...

### ISSUE THREAD

**Issue by ali019283** [ico277/bf2c#2]
...or else i will be angy 😡

**Comment by ali019283** [comment]
im totally friendly tho 😌 🔪 🔪🔪🔪🔪🔪🔪

**Comment by ali019283** [comment]
@ico277 do it NOW 😡 😡 😡

**Comment by adamtherookie** [comment]
LOL what is happening here -_-

**Comment by adamtherookie** [comment]
![image](https://user-images.githubusercontent.com/56547533/137593559-ed13489b-f029-4657-9f0b-617f1e6d4628.png)
Um, I think you should make a CONTRIBUTORS.md file or something...

**Comment by ali019283** [comment]
cope and seethe

**Comment by ico277** [comment]
no
